<a href="https://colab.research.google.com/github/Valdan-D/remorse/blob/Lorenzo/Lorenzo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PROGETTO DATAMANAGEMENT**

---

**Colonne dei datasets**
- occurrence_no: ID univoco dell’occorrenza fossile./
- record_type: tipo di record, di solito occurrence.
- reid_no: ID di eventuale reidentificazione del fossile./
- flags: segnala condizioni particolari del record./
- collection_no: ID della collezione/località fossile./
- identified_name: nome tassonomico identificato originariamente./
- identified_rank: rango tassonomico del nome identificato.
- identified_no: ID del taxon identificato./
- difference: differenza tra nome identificato e nome accettato.
- accepted_name: nome tassonomico accettato dalla PBDB./
- accepted_attr: autore/attribuzione del nome accettato.
- accepted_rank: rango tassonomico del nome accettato.
- accepted_no: ID del taxon accettato./
- early_interval: intervallo geologico iniziale./
- late_interval: intervallo geologico finale, se presente./
- max_ma: età massima stimata in milioni di anni fa./
- min_ma: età minima stimata in milioni di anni fa./
- reference_no: ID della fonte bibliografica.
- lng: longitudine della località fossile./
- lat: latitudine della località fossile./
- cc: codice del paese./
- state: stato, provincia o regione./
- county: contea o area locale./
- latlng_basis: metodo usato per determinare le coordinate./
- latlng_precision: precisione delle coordinate geografiche./
- altitude_value: altitudine della località, se disponibile./
- altitude_unit: unità di misura dell’altitudine./
- geogscale: scala geografica della località./
- geogcomments: commenti sulla posizione geografica.
- cx_int_no: ID dell’intervallo geologico associato./
- formation: formazione geologica del ritrovamento./
- geological_group: gruppo geologico/stratigrafico./
- member: membro stratigrafico più specifico.
- phylum: phylum tassonomico./
- class: classe tassonomica./
- order: ordine tassonomico./
- family: famiglia tassonomica./
- genus: genere tassonomico./

<br>

---

## Setup

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df_dino = pd.read_csv('dinos.csv')
df_plant = pd.read_csv('plants.csv')

## DINO

### Statistiche base del dataset

In [5]:
df_dino.head()

,occurrence_no,record_type,reid_no,flags,collection_no,identified_name,identified_rank,identified_no,difference,accepted_name,...,geogcomments,cx_int_no,formation,geological_group,member,phylum,class,order,family,genus
0,41524,occ,NaN,NaN,3257,Aves indet.,class,NaN,NaN,Aves,...,at Dummer's Copse between Allington Lane and Q...,37.0,NaN,Bracklesham,NaN,Chordata,Aves,NaN,NaN,NaN
1,41580,occ,NaN,NaN,3256,Aves indet.,class,NaN,NaN,Aves,...,"at Dummer's Copse, between Allington Lane and ...",37.0,NaN,Bracklesham,NaN,Chordata,Aves,NaN,NaN,NaN
2,130209,occ,NaN,NaN,10755,Chaoyangosaurus liaosiensis n. gen. n. sp.,species,65704.0,NaN,Chaoyangsaurus youngi,...,"Chaoyang area of Liaoning Province, NE China",2.0,Tuchengzi,NaN,NaN,Chordata,Ornithischia,NO_ORDER_SPECIFIED,Chaoyangsauridae,Chaoyangsaurus
3,130294,occ,NaN,NaN,10764,Protarchaeopteryx robusta n. gen. n. sp.,species,NaN,NaN,Protarchaeopteryx robusta,...,Sihetun area near Beipiao city,40.0,Yixian,Jehol,Jianshangou,Chordata,Reptilia,NO_ORDER_SPECIFIED,NO_FAMILY_SPECIFIED,Protarchaeopteryx
4,130295,occ,NaN,NaN,10764,Caudipteryx zoui n. gen. n. sp.,species,NaN,NaN,Caudipteryx zoui,...,Sihetun area near Beipiao city,40.0,Yixian,Jehol,Jianshangou,Chordata,Reptilia,NO_ORDER_SPECIFIED,NO_FAMILY_SPECIFIED,Caudipteryx

In [6]:
df_dino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37790 entries, 0 to 37789
Data columns (total 38 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   occurrence_no     37790 non-null  int64
 1   record_type       37790 non-null  object
 2   reid_no           4154 non-null   float64
 3   flags             3417 non-null   object
 4   collection_no     37790 non-null  int64
 5   identified_name   37790 non-null  object
 6   identified_rank   37790 non-null  object
 7   identified_no     12703 non-null  float64
 8   difference        3889 non-null   object
 9   accepted_name     37790 non-null  object
 10  accepted_attr     37748 non-null  object
 11  accepted_rank     37790 non-null  object
 12  accepted_no       37790 non-null  int64
 13  early_interval    37790 non-null  object
 14  late_interval     8675 non-null   object
 15  max_ma            37790 non-null  float64
 16  min_ma            37790 non-null  float64
 17  reference_no      37790 non-null  int64
 18  lng               37790 non-null  float64
 19  lat               37790 non-null  float64
 20  cc                37773 non-null  object
 21  state             31470 non-null  object
 22  county            18729 non-null  object
 23  latlng_basis      36179 non-null  object
 24  latlng_precision  37790 non-null  object
 25  altitude_value    8670 non-null   float64
 26  altitude_unit     8579 non-null   object
 27  geogscale         31163 non-null  object
 28  geogcomments      29907 non-null  object
 29  cx_int_no         37728 non-null  float64
 30  formation         23443 non-null  object
 31  geological_group  10352 non-null  object
 32  member            7208 non-null   object
 33  phylum            37790 non-null  object
 34  class             37790 non-null  object
 35  order             30411 non-null  object
 36  family            29067 non-null  object
 37  genus             23558 non-null  object
dtypes: float64(8), int64(4), object(26)
memory usage: 11.0+ MB

In [8]:
df_dino.describe()

,occurrence_no,reid_no,collection_no,identified_no,accepted_no,max_ma,min_ma,reference_no,lng,lat,altitude_value,cx_int_no
count,3.779000e+04,4154.000000,37790.000000,12703.000000,37790.000000,37790.000000,37790.000000,37790.000000,37790.000000,37790.000000,8670.000000,37728.000000
mean,1.111161e+06,30509.549350,122537.062159,210102.997953,136205.014051,71.008821,64.523279,49143.774358,-19.988668,24.989404,991.356055,189.010549
std,4.505221e+05,8840.766784,73859.233773,136267.822972,132610.253551,65.819122,61.616788,26523.281573,92.791387,29.819606,1148.334106,294.044695
min,4.152400e+04,10063.000000,3256.000000,36610.000000,36616.000000,0.011700,0.000000,149.000000,-179.154999,-84.333336,-917.000000,1.000000
25%,6.322072e+05,22477.250000,53074.000000,91970.000000,38831.000000,0.129000,0.011700,24059.000000,-106.646927,18.330000,192.000000,37.000000
50%,1.273561e+06,32464.500000,109831.500000,143772.000000,64125.000000,72.200000,66.000000,55247.500000,-17.858500,37.404999,689.000000,112.000000
75%,1.468913e+06,38361.750000,194642.000000,368309.000000,186242.000000,121.400000,100.500000,70791.000000,35.373600,43.572224,1334.000000,119.000000
max,2.066136e+06,43269.000000,279154.000000,515615.000000,520798.000000,251.902000,248.100000,327912.000000,178.677002,89.039169,10421.000000,1203.000000

### Creazione dataframe dinosauri pulito e utilizzabile

In [11]:
colonne_utili_dino = [
    "occurrence_no",
    "collection_no",
    "accepted_name",
    "accepted_rank",
    "accepted_no",
    "identified_name",
    "early_interval",
    "late_interval",
    "max_ma",
    "min_ma",
    "lng",
    "lat",
    "cc",
    "state",
    "county",
    "latlng_basis",
    "latlng_precision",
    "formation",
    "geological_group",
    "member",
    "phylum",
    "class",
    "order",
    "family",
    "genus",
    "reference_no"
]

df_dino_clean = df_dino[colonne_utili_dino].copy()

In [17]:
df_dino_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37790 entries, 0 to 37789
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   occurrence_no     37790 non-null  int64
 1   collection_no     37790 non-null  int64
 2   accepted_name     37790 non-null  object
 3   accepted_rank     37790 non-null  object
 4   accepted_no       37790 non-null  int64
 5   identified_name   37790 non-null  object
 6   early_interval    37790 non-null  object
 7   late_interval     8675 non-null   object
 8   max_ma            37790 non-null  float64
 9   min_ma            37790 non-null  float64
 10  lng               37790 non-null  float64
 11  lat               37790 non-null  float64
 12  cc                37773 non-null  object
 13  state             31470 non-null  object
 14  county            18729 non-null  object
 15  latlng_basis      36179 non-null  object
 16  latlng_precision  37790 non-null  object
 17  formation         23443 non-null  object
 18  geological_group  10352 non-null  object
 19  member            7208 non-null   object
 20  phylum            37790 non-null  object
 21  class             37790 non-null  object
 22  order             30411 non-null  object
 23  family            29067 non-null  object
 24  genus             23558 non-null  object
 25  reference_no      37790 non-null  int64
dtypes: float64(4), int64(4), object(18)
memory usage: 7.5+ MB

In [12]:
df_dino_clean.isna().sum()

occurrence_no           0
collection_no           0
accepted_name           0
accepted_rank           0
accepted_no             0
identified_name         0
early_interval          0
late_interval       29115
max_ma                  0
min_ma                  0
lng                     0
lat                     0
cc                     17
state                6320
county              19061
latlng_basis         1611
latlng_precision        0
formation           14347
geological_group    27438
member              30582
phylum                  0
class                   0
order                7379
family               8723
genus               14232
reference_no            0
dtype: int64